### ISSUE TITLE
Replicating the results

### ISSUE THREAD

**Issue by mateuk** [Yale-LILY/QMSum#1]
Hello, thanks for sharing the dataset! 

I'm trying to replicate your results, and I'm missing some details, would be great if you could help me.

For BART and PGNet you say in your paper that the input text in truncated to 2048 tokens. 
I get how is the input text constructed for the "∗" and "†" models, but how about the ones without any sign? Are you truncating the whole transcript?

**Comment by maszhongming** [comment]
Thank you very much for your interest! For BART and PGNet, we truncate the input length to 2048 under any setting.
