### ISSUE TITLE
potential data error

### ISSUE THREAD

**Issue by chijames** [Yale-LILY/QMSum#3]
Hi,

In Committee/jsonl/train.jsonl, the last instance in the topic_list is relevant_text_span": [["44", "368"]], but seems like 368 is longer than the meeting_transcripts length?

Thanks.

**Comment by Narabzad** [comment]
I have seen the same thing in the data as well .
In ES2016c.json#L48
one relevant text span is annotated as turn 132-309 however the whole transcript only has 280 turns.

**Comment by maszhongming** [comment]
Thank you so much for pointing out these errors!

They should be ["45", "337"] for covid_1 and ["132", "279"] for ES2016c. We have checked whether the relevant text span is within the scope of the meeting but sorry that there are few meetings (including ES2016c and covid_1) that are our samples as pilot annotations. We missed checking them and this led to such an error. I have fixed them on GitHub. If you find more similar errors, please feel free to contact me and I will fix them as soon as possible.

**Comment by Narabzad** [comment]
Bed004.json#L14
The relevant spans for the topic is not mentioned

I will let you know if I found more issues :)

**Comment by chijames** [comment]
I also spot another one in the first line of Academic/jsonl/train.jsonl: relevant_text_span": [["2. Low", "pass down sampling"]]

@maszhongming Is it possible for you to rerun some sanity checks on the pilot data? I feel it would be better to perform a systematic check on your end instead of us catching some random bugs. There are too many of them!

**Comment by maszhongming** [comment]
Hi @chijames @Narabzad ,

Thank you very much for your help! I have conducted a systematic check and fixed all the error data. Now the "relevant text span" consists entirely of numbers and does not exceed the scope of the meeting. If you find other problems, please feel free to contact me, I will fix them as soon as possible.
