### ISSUE TITLE
clarification on evaluation 

### ISSUE THREAD

**Issue by xwhan** [Yale-LILY/QMSum#5]
Hi @maszhongming @WadeYin9712, 

Thank you for releasing the nice dataset! 

When reporting the metrics, did you follow the rouge evaluation of BART (PTB tokenization + file2rouge)? I'm trying to get comparable numbers.

**Comment by maszhongming** [comment]
Thanks for your interest in our work!

The ROUGE metric we used is pyrouge 0.1.3., which is different from BART.

**Comment by xwhan** [comment]
Can you share your evaluation script? My understanding is that file2rouge is actually calling pyrouge under the hood.

**Comment by maszhongming** [comment]
Sorry I haven't used file2rouge before, and I don't know if it uses pyrouge internally. The metric I use is the same as here: https://github.com/maszhongming/MatchSum/blob/master/metrics.py#L179
